// src/lib/components/button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes, HTMLAnchorAttributes } from 'svelte/elements';

  type Variant = 'primary' | 'secondary' | 'ghost' | 'gradient';

  type Props = {
    variant?: Variant;
    href?: string;
    children: Snippet;
  } & Omit<HTMLButtonAttributes, 'children'> &
    Omit<HTMLAnchorAttributes, 'children'>;

  const { variant = 'primary', href, children, ...rest }: Props = $props();

  const base =
    'inline-flex items-center justify-center gap-2 px-4 py-2 rounded-[10px] font-medium text-sm transition-colors duration-[var(--duration-standard)] ease-[var(--ease-out)] disabled:opacity-50';

  const variants: Record<Variant, string> = {
    primary: 'bg-[var(--color-accent)] text-white hover:bg-[var(--color-accent-hover)]',
    secondary:
      'bg-[var(--color-surface-2)] text-[var(--color-ink)] hover:bg-[var(--color-border)] border border-[var(--color-border)]',
    ghost:
      'bg-transparent text-[var(--color-ink)] hover:bg-[var(--color-surface-2)]',
    gradient: 'text-white bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)]'
  };

  const cls = $derived(`${base} ${variants[variant]}`);
</script>

{#if href}
  <a {href} class={cls} {...rest}>{@render children()}</a>
{:else}
  <button class={cls} {...rest}>{@render children()}</button>
{/if}

// src/components/ui/button.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { cn } from '@/lib/utils';

type Variant = 'primary' | 'secondary' | 'ghost' | 'outline' | 'destructive';
type Size = 'sm' | 'md' | 'lg';

interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant;
  size?: Size;
}

const variants: Record<Variant, string> = {
  primary:
    'bg-[color:var(--primary)] text-[color:var(--primary-foreground)] hover:opacity-90',
  secondary: 'bg-[color:var(--muted)] text-[color:var(--foreground)] hover:opacity-90',
  ghost: 'bg-transparent hover:bg-[color:var(--muted)]',
  outline:
    'border border-[color:var(--border)] bg-transparent hover:bg-[color:var(--muted)]',
  destructive: 'bg-red-600 text-white hover:bg-red-700',
};

const sizes: Record<Size, string> = {
  sm: 'h-8 px-3 text-sm rounded-md',
  md: 'h-10 px-4 text-sm rounded-lg',
  lg: 'h-12 px-6 text-base rounded-xl',
};

export const Button = forwardRef<HTMLButtonElement, Props>(function Button(
  { className, variant = 'primary', size = 'md', ...props },
  ref,
) {
  return (
    <button
      ref={ref}
      className={cn(
        'inline-flex items-center justify-center gap-2 font-medium transition disabled:opacity-50 disabled:pointer-events-none',
        variants[variant],
        sizes[size],
        className,
      )}
      {...props}
    />
  );
});
